-- 코드를 작성해주세요

with recursive cte as
    (select ID, PARENT_ID, 1 AS GENERATION
     FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, CTE.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN CTE ON E.PARENT_ID=CTE.ID)
    
SELECT ID
FROM CTE
WHERE GENERATION=3
ORDER BY ID ASC