-- 코드를 입력하세요
SELECT  
        YEAR(OS.SALES_DATE) AS YEAR,
        MONTH(OS.SALES_DATE) AS MONTH,
        COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT OS.USER_ID)/(SELECT COUNT(DISTINCT USER_ID)
                                         FROM USER_INFO
                                         WHERE YEAR(JOINED)=2021), 1) AS PURCHASED_RATIO
    FROM ONLINE_SALE AS OS
    JOIN USER_INFO AS UI
    ON OS.USER_ID = UI.USER_ID
    WHERE YEAR(UI.JOINED)=2021
    GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE);