-- 코드를 작성해주세요
WITH RECURSIVE CTE AS
    (SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, CTE.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN CTE ON E.PARENT_ID=CTE.ID)
    
SELECT COUNT(*) AS COUNT, CTE.GENERATION
    FROM CTE
    LEFT JOIN ECOLI_DATA AS CHILD
    ON CTE.ID = CHILD.PARENT_ID
    WHERE CHILD.ID IS NULL
    GROUP BY CTE.GENERATION
    ORDER BY CTE.GENERATION