-- 코드를 입력하세요
SELECT  AP.APNT_NO, 
        PT.PT_NAME, 
        PT.PT_NO,
        DR.MCDP_CD,
        DR.DR_NAME,
        AP.APNT_YMD
    FROM APPOINTMENT AS AP
    LEFT JOIN DOCTOR AS DR ON AP.MDDR_ID = DR.DR_ID 
    LEFT JOIN PATIENT AS PT ON AP.PT_NO = PT.PT_NO
WHERE   AP.MCDP_CD like 'CS'
        AND AP.APNT_YMD LIKE '2022-04-13%'
        AND AP.APNT_CNCL_YN = 'N'
ORDER BY AP.APNT_YMD ASC