-- 코드를 입력하세요
SELECT  UGB.TITLE,
        UGB.BOARD_ID,
        UGR.REPLY_ID,
        UGR.WRITER_ID,
        UGR.CONTENTS,
        DATE_FORMAT(UGR.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
    FROM (SELECT    *
            FROM USED_GOODS_BOARD
            WHERE YEAR(CREATED_DATE)="2022" AND MONTH(CREATED_DATE)="10") AS UGB
    JOIN USED_GOODS_REPLY AS UGR
    ON UGB.BOARD_ID=UGR.BOARD_ID
    ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC;