-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
# SELECT *
FROM (SELECT *
      FROM BOOK_SALES
      WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=01)
      AS BS
JOIN BOOK AS B
ON B.BOOK_ID=BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY